---
- name: Delete route
  changed_when: no
  command: "{{ route_if_down_script }}"
  environment:
    IFACE: "{{ interface.name }}"
  when: route_network in ip_route_result.stdout

- name: Remove if-up script
  file:
    path: "{{ route_if_up_script }}"
    state: absent

- name: Remove if-down script
  file:
    path: "{{ route_if_down_script }}"
    state: absent
